### ISSUE TITLE
Epic 3 : Testing for Photo Uploading Feature

### ISSUE THREAD

**Issue by Sharu201101** [BitBytes-team/project7#9]
As a developer, I want the assignee to perform testing for the recently implemented Photo Uploading feature, so that we can ensure the feature functions correctly and is free from defects. 

Test Criteria: 

- Create test cases to cover the Photo Uploading feature, including various scenarios such as successful photo uploads, error handling, and edge cases. 
- Verify that users can successfully upload photos through the user interface by using automated tests to simulate user interactions. 
- Validate that photos are stored securely and associated with the correct user accounts. 
- Ensure that appropriate error messages are displayed when file uploads fail due to different reasons, such as file size exceeding limits, unsupported file types, or server issues. 
- Conduct load testing to verify that the system can handle a high volume of photo uploads without performance degradation. 
- Validate that the photo upload feature integrates seamlessly with other parts of the application, such as displaying uploaded photos in the user's gallery or profile. 
- Regression test the feature after any bug fixes or code changes and ensure that new code changes do not introduce new defects. 
- Confirm that the Photo Uploading feature aligns with the defined project requirements and user story acceptance criteria.

**Comment by Jahnavi-0305** [comment]
I am done with the review. kindly move it to the test phase

**Comment by suhasss077** [comment]
The above test cases are being tested and will let you know the result.

**Comment by suhasss077** [comment]
- Verified that users can successfully upload photos through the user interface by using automated tests to simulate user interactions.
- Validated that photos are stored securely and associated with the correct user accounts.
- Ensured that appropriate error messages are displayed when file uploads fail due to different reasons, such as file size exceeding limits, unsupported file types, or server issues.
- Photo Uploading feature aligns with the defined project requirements and user story acceptance criteria.
